wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.14
    start_time: 1763318895.470451
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.14
      5: 0.13.0
      8:
      - 4
      - 5
algorithm:
  desc: null
  value: PPO
environment:
  desc: null
  value: CartPole-v1
hidden_dim:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0003
schedule:
  desc: null
  value: oneshot_before
target_prune_ratio:
  desc: null
  value: 0.85
technique:
  desc: null
  value: magnitude_weight
train_batch_size:
  desc: null
  value: 4000
