_wandb:
    value:
        cli_version: 0.23.1
        e:
            6h9s3ivf60ntf4ytwqt4euzxkkhrah2l:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "119879979008"
                email: mahaoming8585485@163.com
                executable: /home/mhm/.pyenv/versions/3.10.14/bin/python
                git:
                    commit: 6ec0f41379bbe75bb2b22fdae122d00fce47c5d3
                    remote: https://github.com/ma-h-m/rllib-accelerator/
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-3da99c43-a9ce-dd1f-18e3-c4f223772f96
                host: DESKTOP-3PG5ACS
                memory:
                    total: "16269934592"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/mhm/workspace/rllib-accelerator/main.py
                python: CPython 3.10.14
                root: /home/mhm/workspace/rllib-accelerator
                startedAt: "2025-12-05T16:03:11.076557Z"
                writerId: 6h9s3ivf60ntf4ytwqt4euzxkkhrah2l
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 30
            "2":
                - 1
                - 30
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
compile_mode:
    value: none
device:
    value: cpu
enable_diff_check:
    value: false
env_id:
    value: CartPole-v1
experiment:
    value: baseline
trigger_every:
    value: 0
