name: rllib-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lazy-loader==0.4
      - lz4==4.4.5
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.2.1
      - numpy==1.25.2
      - ormsgpack==1.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pathtools==0.1.2
      - pillow==11.3.0
      - pip==25.3
      - promise==2.3
      - protobuf==3.20.3
      - psutil==7.1.3
      - pyarrow==12.0.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygame==2.1.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==2.9.3
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - scikit-image==0.24.0
      - scipy==1.13.1
      - sentry-sdk==2.44.0
      - setproctitle==1.3.7
      - setuptools==69.5.1
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - tifffile==2024.8.30
      - torch==2.8.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.13.0
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/rllib-env
