_wandb:
    value:
        cli_version: 0.23.1
        e:
            gse5wgt6ow58254z3y9pjui3oxz09a7c:
                email: fm2859@columbia.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 820ece4e2acdb2f2072ee598041a0916decb6d73
                    remote: https://github.com/ma-h-m/rllib-accelerator.git
                host: fionas-MacBook-Pro-2.local
                os: macOS-26.1-arm64-arm-64bit
                program: <python with no main file>
                python: CPython 3.12.2
                root: /Users/fionameng/Documents/rllib-accelerator/wandb_logs
                startedAt: "2025-12-17T02:21:53.956589Z"
                writerId: gse5wgt6ow58254z3y9pjui3oxz09a7c
        m: []
        python_version: 3.12.2
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
test:
    value: value
